# Usamos la imagen base de OpenJDK 21 en Alpine para menor tamaño
FROM eclipse-temurin:21-jdk-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el JAR construido a la imagen
COPY target/Tienda-App-0.0.1-SNAPSHOT.jar app.jar

# Exponemos el puerto en el que correrá la app
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
